-- MySQL Script generated by MySQL Workbench
-- Mon Jun  5 18:30:18 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Aseguradoras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Aseguradoras` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Aseguradoras` (
  `nombre_A` VARCHAR(45) NOT NULL,
  `nombreDueño_A` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre_A`, `nombreDueño_A`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `DNI_C` INT(8) NOT NULL,
  `Telefono_C` INT(9) NOT NULL,
  `Email_C` VARCHAR(45) NULL,
  `Nombre_C` VARCHAR(45) NULL,
  PRIMARY KEY (`DNI_C`),
  UNIQUE INDEX `Telefono_C_UNIQUE` (`Telefono_C` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sede`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Sede` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Sede` (
  `identificador_S` INT NOT NULL,
  `Direccion_S` VARCHAR(90) NOT NULL,
  `fechaApertura_S` DATE NULL DEFAULT '2000-01-01',
  PRIMARY KEY (`identificador_S`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vehículo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Vehículo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Vehículo` (
  `Matricula_V` VARCHAR(7) NOT NULL,
  `Marca_V` VARCHAR(20) NOT NULL,
  `Modelo_V` VARCHAR(20) NULL,
  `Caracteristicas_V` VARCHAR(200) NULL,
  `Sede_identificador_S` INT NOT NULL,
  PRIMARY KEY (`Matricula_V`),
  INDEX `fk_Vehículo_Sede1_idx` (`Sede_identificador_S` ASC) VISIBLE,
  CONSTRAINT `fk_Vehículo_Sede1`
    FOREIGN KEY (`Sede_identificador_S`)
    REFERENCES `mydb`.`Sede` (`identificador_S`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mantenimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Mantenimiento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Mantenimiento` (
  `Identificador_M` INT NOT NULL,
  `Descripcion_M` VARCHAR(200) NULL,
  `Fecha_M` DATE NOT NULL,
  `Vehículo_Matricula_V` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`Identificador_M`),
  INDEX `fk_Mantenimiento_Vehículo1_idx` (`Vehículo_Matricula_V` ASC) VISIBLE,
  CONSTRAINT `fk_Mantenimiento_Vehículo1`
    FOREIGN KEY (`Vehículo_Matricula_V`)
    REFERENCES `mydb`.`Vehículo` (`Matricula_V`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Coche`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Coche` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Coche` (
  `Puertas_Co` INT NULL DEFAULT 4,
  `Matricula_V` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`Matricula_V`),
  CONSTRAINT `fk_Coche_Matricula_V`
    FOREIGN KEY (`Matricula_V`)
    REFERENCES `mydb`.`Vehículo` (`Matricula_V`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Moto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Moto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Moto` (
  `Alforjas_Mo` INT NULL DEFAULT 0,
  `Matricula_V` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`Matricula_V`),
  CONSTRAINT `fk_Moto_Matricula_V`
    FOREIGN KEY (`Matricula_V`)
    REFERENCES `mydb`.`Vehículo` (`Matricula_V`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Camion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Camion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Camion` (
  `PesoMax_Ca` DOUBLE NULL,
  `Matricula_V` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`Matricula_V`),
  CONSTRAINT `fk_Camion_Matricula_V`
    FOREIGN KEY (`Matricula_V`)
    REFERENCES `mydb`.`Vehículo` (`Matricula_V`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Alquila`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Alquila` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Alquila` (
  `Vehículo_Matricula_V` VARCHAR(7) NOT NULL,
  `Cliente_DNI_C` INT(8) NOT NULL,
  `FechaAlquiler_CV` DATE NOT NULL,
  `Duracion_CV` INT UNSIGNED NOT NULL DEFAULT 1,
  `Precio_CV` INT UNSIGNED NULL,
  PRIMARY KEY (`Vehículo_Matricula_V`, `Cliente_DNI_C`, `FechaAlquiler_CV`),
  INDEX `fk_Vehículo_has_Cliente_Cliente1_idx` (`Cliente_DNI_C` ASC) VISIBLE,
  INDEX `fk_Vehículo_has_Cliente_Vehículo1_idx` (`Vehículo_Matricula_V` ASC) VISIBLE,
  CONSTRAINT `fk_Vehículo_has_Cliente_Vehículo1`
    FOREIGN KEY (`Vehículo_Matricula_V`)
    REFERENCES `mydb`.`Vehículo` (`Matricula_V`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vehículo_has_Cliente_Cliente1`
    FOREIGN KEY (`Cliente_DNI_C`)
    REFERENCES `mydb`.`Cliente` (`DNI_C`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ayuda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ayuda` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ayuda` (
  `identificadorDonante_S` INT NOT NULL,
  `identificadorRecibe_S` INT NOT NULL,
  `FechaAyuda_SS` DATE NULL,
  `Cantidad_SS` INT UNSIGNED NULL,
  PRIMARY KEY (`identificadorDonante_S`, `identificadorRecibe_S`),
  INDEX `fk_Sede_has_Sede_Sede2_idx` (`identificadorRecibe_S` ASC) VISIBLE,
  INDEX `fk_Sede_has_Sede_Sede1_idx` (`identificadorDonante_S` ASC) VISIBLE,
  CONSTRAINT `fk_Sede_has_Sede_Sede1`
    FOREIGN KEY (`identificadorDonante_S`)
    REFERENCES `mydb`.`Sede` (`identificador_S`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sede_has_Sede_Sede2`
    FOREIGN KEY (`identificadorRecibe_S`)
    REFERENCES `mydb`.`Sede` (`identificador_S`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`asegura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`asegura` ;

CREATE TABLE IF NOT EXISTS `mydb`.`asegura` (
  `Matricula_V` VARCHAR(7) NOT NULL,
  `Nombre_A` VARCHAR(45) NOT NULL,
  `NombreDueño_A` VARCHAR(45) NOT NULL,
  `DNI_C` INT(8) NOT NULL,
  `FechaAlquiler_CVA` DATE NOT NULL,
  `PrecioSeguro_CVA` FLOAT NOT NULL DEFAULT 0.0,
  PRIMARY KEY (`Matricula_V`, `Nombre_A`, `NombreDueño_A`, `DNI_C`, `FechaAlquiler_CVA`),
  INDEX `DNIC_C_idx` (`DNI_C` ASC) VISIBLE,
  INDEX `Nombre_A_idx` (`Nombre_A` ASC) VISIBLE,
  INDEX `NombreDueño_A_idx` (`NombreDueño_A` ASC) VISIBLE,
  CONSTRAINT `fk_asegura_Matricula_V`
    FOREIGN KEY (`Matricula_V`)
    REFERENCES `mydb`.`Vehículo` (`Matricula_V`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asegura_DNI_C`
    FOREIGN KEY (`DNI_C`)
    REFERENCES `mydb`.`Cliente` (`DNI_C`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asegura_Aseguradora`
    FOREIGN KEY (`Nombre_A` , `NombreDueño_A`)
    REFERENCES `mydb`.`Aseguradoras` (`nombre_A` , `nombreDueño_A`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`Aseguradoras`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Aseguradoras` (`nombre_A`, `nombreDueño_A`) VALUES ('Seguros del Norte', 'Pedro Martinez ');
INSERT INTO `mydb`.`Aseguradoras` (`nombre_A`, `nombreDueño_A`) VALUES ('Protección Total', 'Fernando Alonso');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Cliente`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Cliente` (`DNI_C`, `Telefono_C`, `Email_C`, `Nombre_C`) VALUES (123456789, 612345678, 'cliente1@example.com', 'Juan Pérez');
INSERT INTO `mydb`.`Cliente` (`DNI_C`, `Telefono_C`, `Email_C`, `Nombre_C`) VALUES (987654321, 623456789, 'cliente2@example.com', 'María López');
INSERT INTO `mydb`.`Cliente` (`DNI_C`, `Telefono_C`, `Email_C`, `Nombre_C`) VALUES (456789123, 634567890, 'cliente3@example.com', 'Carlos Ramírez');
INSERT INTO `mydb`.`Cliente` (`DNI_C`, `Telefono_C`, `Email_C`, `Nombre_C`) VALUES (321654987, 645678901, 'cliente4@example.com', 'Laura Torres');
INSERT INTO `mydb`.`Cliente` (`DNI_C`, `Telefono_C`, `Email_C`, `Nombre_C`) VALUES (789123456, 656789012, 'cliente5@example.com', 'Andrés Gómez');
INSERT INTO `mydb`.`Cliente` (`DNI_C`, `Telefono_C`, `Email_C`, `Nombre_C`) VALUES (654987321, 667890123, 'cliente6@example.com', 'Ana Rodríguez');
INSERT INTO `mydb`.`Cliente` (`DNI_C`, `Telefono_C`, `Email_C`, `Nombre_C`) VALUES (987123456, 678901234, 'cliente7@example.com', 'Javier Sánchez');
INSERT INTO `mydb`.`Cliente` (`DNI_C`, `Telefono_C`, `Email_C`, `Nombre_C`) VALUES (456321987, 689012345, 'cliente8@example.com', 'Sofía Herrera');
INSERT INTO `mydb`.`Cliente` (`DNI_C`, `Telefono_C`, `Email_C`, `Nombre_C`) VALUES (321789654, 690123456, 'cliente9@example.com', 'Luis Martínez');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Sede`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Sede` (`identificador_S`, `Direccion_S`, `fechaApertura_S`) VALUES (1, 'Calle Principal 123	', str_to_date('01/01/2020', '%d/%m/%Y'));
INSERT INTO `mydb`.`Sede` (`identificador_S`, `Direccion_S`, `fechaApertura_S`) VALUES (2, 'Avenida Central 456', str_to_date('15/03/2020', '%d/%m/%Y'));
INSERT INTO `mydb`.`Sede` (`identificador_S`, `Direccion_S`, `fechaApertura_S`) VALUES (3, 'Plaza Mayor 789', str_to_date('01/01/2020', '%d/%m/%Y'));
INSERT INTO `mydb`.`Sede` (`identificador_S`, `Direccion_S`, `fechaApertura_S`) VALUES (4, 'Paseo del Sol 234', str_to_date('25/09/2020', '%d/%m/%Y'));

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Vehículo`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Vehículo` (`Matricula_V`, `Marca_V`, `Modelo_V`, `Caracteristicas_V`, `Sede_identificador_S`) VALUES ('ABCD123', 'Ford', 'Mustang', 'Motor de 5.0L, tracción trasera', 1);
INSERT INTO `mydb`.`Vehículo` (`Matricula_V`, `Marca_V`, `Modelo_V`, `Caracteristicas_V`, `Sede_identificador_S`) VALUES ('EFGH456', 'Ford', 'Mustang', 'Motor de 5.0L, tracción trasera', 2);
INSERT INTO `mydb`.`Vehículo` (`Matricula_V`, `Marca_V`, `Modelo_V`, `Caracteristicas_V`, `Sede_identificador_S`) VALUES ('IJKL789', 'Toyota', 'Corolla', '	Motor de 2.0L, tracción delantera', 3);
INSERT INTO `mydb`.`Vehículo` (`Matricula_V`, `Marca_V`, `Modelo_V`, `Caracteristicas_V`, `Sede_identificador_S`) VALUES ('MNOP012', 'Toyota', 'Corolla', '	Motor de 2.0L, tracción delantera', 4);
INSERT INTO `mydb`.`Vehículo` (`Matricula_V`, `Marca_V`, `Modelo_V`, `Caracteristicas_V`, `Sede_identificador_S`) VALUES ('QRST345', 'Honda', 'Civic', '	Motor híbrido, eficiencia energética', 1);
INSERT INTO `mydb`.`Vehículo` (`Matricula_V`, `Marca_V`, `Modelo_V`, `Caracteristicas_V`, `Sede_identificador_S`) VALUES ('UVWX678', 'Honda', 'Civic', '	Motor híbrido, eficiencia energética', 2);
INSERT INTO `mydb`.`Vehículo` (`Matricula_V`, `Marca_V`, `Modelo_V`, `Caracteristicas_V`, `Sede_identificador_S`) VALUES ('YZAB901', 'Ford', 'Fiesta', '	Motor de 1.5L, sistema de entretenimiento', 3);
INSERT INTO `mydb`.`Vehículo` (`Matricula_V`, `Marca_V`, `Modelo_V`, `Caracteristicas_V`, `Sede_identificador_S`) VALUES ('CDEF234', 'Ford', 'Fiesta', '	Motor de 1.5L, sistema de entretenimiento', 4);
INSERT INTO `mydb`.`Vehículo` (`Matricula_V`, `Marca_V`, `Modelo_V`, `Caracteristicas_V`, `Sede_identificador_S`) VALUES ('GHIJ567', 'BMW', 'Serie 3', '	Motor de 3.0L, tracción trasera', 1);
INSERT INTO `mydb`.`Vehículo` (`Matricula_V`, `Marca_V`, `Modelo_V`, `Caracteristicas_V`, `Sede_identificador_S`) VALUES ('KLMN890', 'BMW', 'Serie 3', '	Motor de 3.0L, tracción trasera', 2);
INSERT INTO `mydb`.`Vehículo` (`Matricula_V`, `Marca_V`, `Modelo_V`, `Caracteristicas_V`, `Sede_identificador_S`) VALUES ('OPQR123', 'Toyota', 'Camry', 'Motor de 2.5L, tracción delantera', 3);
INSERT INTO `mydb`.`Vehículo` (`Matricula_V`, `Marca_V`, `Modelo_V`, `Caracteristicas_V`, `Sede_identificador_S`) VALUES ('STUV456', 'Toyota', 'Camry', 'Motor de 2.5L, tracción delantera', 4);
INSERT INTO `mydb`.`Vehículo` (`Matricula_V`, `Marca_V`, `Modelo_V`, `Caracteristicas_V`, `Sede_identificador_S`) VALUES ('WXYZ789', 'Ford', 'Mustang', 'Motor de 5.0L, tracción trasera', 1);
INSERT INTO `mydb`.`Vehículo` (`Matricula_V`, `Marca_V`, `Modelo_V`, `Caracteristicas_V`, `Sede_identificador_S`) VALUES ('ABCD012', 'Ford', 'Mustang', 'Motor de 5.0L, tracción trasera', 2);
INSERT INTO `mydb`.`Vehículo` (`Matricula_V`, `Marca_V`, `Modelo_V`, `Caracteristicas_V`, `Sede_identificador_S`) VALUES ('EFGH345', 'Honda', 'Accord', '	Motor turbo de 1.5L, control de crucero', 3);
INSERT INTO `mydb`.`Vehículo` (`Matricula_V`, `Marca_V`, `Modelo_V`, `Caracteristicas_V`, `Sede_identificador_S`) VALUES ('IJKL678', 'Honda', 'Accord', '	Motor turbo de 1.5L, control de crucero', 4);
INSERT INTO `mydb`.`Vehículo` (`Matricula_V`, `Marca_V`, `Modelo_V`, `Caracteristicas_V`, `Sede_identificador_S`) VALUES ('AAAA111', 'Yamaha', 'YZF-R1', NULL, 1);
INSERT INTO `mydb`.`Vehículo` (`Matricula_V`, `Marca_V`, `Modelo_V`, `Caracteristicas_V`, `Sede_identificador_S`) VALUES ('BBBB222', 'Yamaha', 'MT-07', NULL, 1);
INSERT INTO `mydb`.`Vehículo` (`Matricula_V`, `Marca_V`, `Modelo_V`, `Caracteristicas_V`, `Sede_identificador_S`) VALUES ('CCCC333', 'Volvo ', 'VNL 860', NULL, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Mantenimiento`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Mantenimiento` (`Identificador_M`, `Descripcion_M`, `Fecha_M`, `Vehículo_Matricula_V`) VALUES (1, 'Cambio de aceite', str_to_date('01/03/2020', '%d/%m/%Y'), 'ABCD123');
INSERT INTO `mydb`.`Mantenimiento` (`Identificador_M`, `Descripcion_M`, `Fecha_M`, `Vehículo_Matricula_V`) VALUES (2, 'Reemplazo de frenos', str_to_date('01/03/2020', '%d/%m/%Y'), 'ABCD123');
INSERT INTO `mydb`.`Mantenimiento` (`Identificador_M`, `Descripcion_M`, `Fecha_M`, `Vehículo_Matricula_V`) VALUES (3, 'Cambio de aceite', str_to_date('15/07/2020', '%d/%m/%Y'), 'ABCD123');
INSERT INTO `mydb`.`Mantenimiento` (`Identificador_M`, `Descripcion_M`, `Fecha_M`, `Vehículo_Matricula_V`) VALUES (4, 'Alineación de ruedas', str_to_date('01/01/2021', '%d/%m/%Y'), 'ABCD123');
INSERT INTO `mydb`.`Mantenimiento` (`Identificador_M`, `Descripcion_M`, `Fecha_M`, `Vehículo_Matricula_V`) VALUES (5, 'Alineación de ruedas', str_to_date('25/04/2020', '%d/%m/%Y'), 'QRST345');
INSERT INTO `mydb`.`Mantenimiento` (`Identificador_M`, `Descripcion_M`, `Fecha_M`, `Vehículo_Matricula_V`) VALUES (6, 'Cambio de batería', str_to_date('25/04/2020', '%d/%m/%Y'), 'QRST345');
INSERT INTO `mydb`.`Mantenimiento` (`Identificador_M`, `Descripcion_M`, `Fecha_M`, `Vehículo_Matricula_V`) VALUES (7, 'Alineación de ruedas', str_to_date('31/08/2021', '%d/%m/%Y'), 'QRST345');
INSERT INTO `mydb`.`Mantenimiento` (`Identificador_M`, `Descripcion_M`, `Fecha_M`, `Vehículo_Matricula_V`) VALUES (8, 'Cambio de aceite', str_to_date('01/03/2020', '%d/%m/%Y'), 'IJKL789');
INSERT INTO `mydb`.`Mantenimiento` (`Identificador_M`, `Descripcion_M`, `Fecha_M`, `Vehículo_Matricula_V`) VALUES (9, 'Reemplazo de frenos', str_to_date('01/03/2020', '%d/%m/%Y'), 'IJKL789');
INSERT INTO `mydb`.`Mantenimiento` (`Identificador_M`, `Descripcion_M`, `Fecha_M`, `Vehículo_Matricula_V`) VALUES (10, 'Mantenimiento general', str_to_date('01/01/2021', '%d/%m/%Y'), 'IJKL789');
INSERT INTO `mydb`.`Mantenimiento` (`Identificador_M`, `Descripcion_M`, `Fecha_M`, `Vehículo_Matricula_V`) VALUES (11, 'Reparación carrocería', str_to_date('01/03/2020', '%d/%m/%Y'), 'GHIJ567');
INSERT INTO `mydb`.`Mantenimiento` (`Identificador_M`, `Descripcion_M`, `Fecha_M`, `Vehículo_Matricula_V`) VALUES (12, 'Mantenimiento general', str_to_date('01/01/2021', '%d/%m/%Y'), 'GHIJ567');
INSERT INTO `mydb`.`Mantenimiento` (`Identificador_M`, `Descripcion_M`, `Fecha_M`, `Vehículo_Matricula_V`) VALUES (13, 'Reparación carrocería', str_to_date('20/03/2020', '%d/%m/%Y'), 'KLMN890');
INSERT INTO `mydb`.`Mantenimiento` (`Identificador_M`, `Descripcion_M`, `Fecha_M`, `Vehículo_Matricula_V`) VALUES (14, 'Cambio de aceite	', str_to_date('15/07/2020', '%d/%m/%Y'), 'KLMN890');
INSERT INTO `mydb`.`Mantenimiento` (`Identificador_M`, `Descripcion_M`, `Fecha_M`, `Vehículo_Matricula_V`) VALUES (15, 'Alineación de ruedas', str_to_date('09/09/2021', '%d/%m/%Y'), 'EFGH345');
INSERT INTO `mydb`.`Mantenimiento` (`Identificador_M`, `Descripcion_M`, `Fecha_M`, `Vehículo_Matricula_V`) VALUES (16, 'Reparación de motor', str_to_date('09/09/2021', '%d/%m/%Y'), 'EFGH345');
INSERT INTO `mydb`.`Mantenimiento` (`Identificador_M`, `Descripcion_M`, `Fecha_M`, `Vehículo_Matricula_V`) VALUES (17, 'Reemplazo de frenos', str_to_date('30/01/2021', '%d/%m/%Y'), 'CDEF234');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Coche`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Coche` (`Puertas_Co`, `Matricula_V`) VALUES (2, 'YZAB901');
INSERT INTO `mydb`.`Coche` (`Puertas_Co`, `Matricula_V`) VALUES (4, 'WXYZ789');
INSERT INTO `mydb`.`Coche` (`Puertas_Co`, `Matricula_V`) VALUES (4, 'UVWX678');
INSERT INTO `mydb`.`Coche` (`Puertas_Co`, `Matricula_V`) VALUES (4, 'STUV456');
INSERT INTO `mydb`.`Coche` (`Puertas_Co`, `Matricula_V`) VALUES (4, 'QRST345');
INSERT INTO `mydb`.`Coche` (`Puertas_Co`, `Matricula_V`) VALUES (4, 'OPQR123');
INSERT INTO `mydb`.`Coche` (`Puertas_Co`, `Matricula_V`) VALUES (4, 'MNOP012');
INSERT INTO `mydb`.`Coche` (`Puertas_Co`, `Matricula_V`) VALUES (4, 'KLMN890');
INSERT INTO `mydb`.`Coche` (`Puertas_Co`, `Matricula_V`) VALUES (4, 'IJKL789');
INSERT INTO `mydb`.`Coche` (`Puertas_Co`, `Matricula_V`) VALUES (4, 'IJKL678');
INSERT INTO `mydb`.`Coche` (`Puertas_Co`, `Matricula_V`) VALUES (4, 'GHIJ567');
INSERT INTO `mydb`.`Coche` (`Puertas_Co`, `Matricula_V`) VALUES (4, 'EFGH456');
INSERT INTO `mydb`.`Coche` (`Puertas_Co`, `Matricula_V`) VALUES (4, 'EFGH345');
INSERT INTO `mydb`.`Coche` (`Puertas_Co`, `Matricula_V`) VALUES (2, 'CDEF234');
INSERT INTO `mydb`.`Coche` (`Puertas_Co`, `Matricula_V`) VALUES (4, 'ABCD123');
INSERT INTO `mydb`.`Coche` (`Puertas_Co`, `Matricula_V`) VALUES (4, 'ABCD012');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Camion`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Camion` (`PesoMax_Ca`, `Matricula_V`) VALUES (100000, 'CCCC333');

COMMIT;

-- -----------------------------------------------------
-- Data for table `mydb`.`Moto`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Moto` (`Alforjas_Mo`, `Matricula_V`) VALUES (0, 'AAAA111');
INSERT INTO `mydb`.`Moto` (`Alforjas_Mo`, `Matricula_V`) VALUES (2, 'BBBB222');
COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Alquila`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Alquila` (`Vehículo_Matricula_V`, `Cliente_DNI_C`, `FechaAlquiler_CV`, `Duracion_CV`, `Precio_CV`) VALUES ('ABCD012', 123456789, str_to_date('10/01/2020', '%d/%m/%Y'), 1, 50);
INSERT INTO `mydb`.`Alquila` (`Vehículo_Matricula_V`, `Cliente_DNI_C`, `FechaAlquiler_CV`, `Duracion_CV`, `Precio_CV`) VALUES ('ABCD012', 456789123, str_to_date('14/05/2020', '%d/%m/%Y'), 2, 90);
INSERT INTO `mydb`.`Alquila` (`Vehículo_Matricula_V`, `Cliente_DNI_C`, `FechaAlquiler_CV`, `Duracion_CV`, `Precio_CV`) VALUES ('ABCD012', 456789123, str_to_date('14/05/2021', '%d/%m/%Y'), 4, 170);
INSERT INTO `mydb`.`Alquila` (`Vehículo_Matricula_V`, `Cliente_DNI_C`, `FechaAlquiler_CV`, `Duracion_CV`, `Precio_CV`) VALUES ('QRST345', 321654987, str_to_date('10/04/2020', '%d/%m/%Y'), 1, 50);
INSERT INTO `mydb`.`Alquila` (`Vehículo_Matricula_V`, `Cliente_DNI_C`, `FechaAlquiler_CV`, `Duracion_CV`, `Precio_CV`) VALUES ('QRST345', 456789123, str_to_date('25/12/2020', '%d/%m/%Y'), 2, 90);
INSERT INTO `mydb`.`Alquila` (`Vehículo_Matricula_V`, `Cliente_DNI_C`, `FechaAlquiler_CV`, `Duracion_CV`, `Precio_CV`) VALUES ('EFGH345', 987654321, str_to_date('12/11/2020', '%d/%m/%Y'), 6, 220);
INSERT INTO `mydb`.`Alquila` (`Vehículo_Matricula_V`, `Cliente_DNI_C`, `FechaAlquiler_CV`, `Duracion_CV`, `Precio_CV`) VALUES ('EFGH345', 321654987, str_to_date('19/10/2020', '%d/%m/%Y'), 1, 50);
INSERT INTO `mydb`.`Alquila` (`Vehículo_Matricula_V`, `Cliente_DNI_C`, `FechaAlquiler_CV`, `Duracion_CV`, `Precio_CV`) VALUES ('IJKL678', 789123456, str_to_date('15/08/2021', '%d/%m/%Y'), 1, 50);
INSERT INTO `mydb`.`Alquila` (`Vehículo_Matricula_V`, `Cliente_DNI_C`, `FechaAlquiler_CV`, `Duracion_CV`, `Precio_CV`) VALUES ('EFGH345', 789123456, str_to_date('16/08/2021', '%d/%m/%Y'), 1, 50);
INSERT INTO `mydb`.`Alquila` (`Vehículo_Matricula_V`, `Cliente_DNI_C`, `FechaAlquiler_CV`, `Duracion_CV`, `Precio_CV`) VALUES ('UVWX678', 789123456, str_to_date('17/08/2021', '%d/%m/%Y'), 1, 50);
INSERT INTO `mydb`.`Alquila` (`Vehículo_Matricula_V`, `Cliente_DNI_C`, `FechaAlquiler_CV`, `Duracion_CV`, `Precio_CV`) VALUES ('QRST345', 789123456, str_to_date('18/08/2021', '%d/%m/%Y'), 1, 50);
INSERT INTO `mydb`.`Alquila` (`Vehículo_Matricula_V`, `Cliente_DNI_C`, `FechaAlquiler_CV`, `Duracion_CV`, `Precio_CV`) VALUES ('MNOP012', 654987321, str_to_date('14/02/2021', '%d/%m/%Y'), 2, 90);
INSERT INTO `mydb`.`Alquila` (`Vehículo_Matricula_V`, `Cliente_DNI_C`, `FechaAlquiler_CV`, `Duracion_CV`, `Precio_CV`) VALUES ('KLMN890', 987123456, str_to_date('31/10/2020', '%d/%m/%Y'), 3, 135);
INSERT INTO `mydb`.`Alquila` (`Vehículo_Matricula_V`, `Cliente_DNI_C`, `FechaAlquiler_CV`, `Duracion_CV`, `Precio_CV`) VALUES ('CDEF234', 456321987, str_to_date('06/01/2021', '%d/%m/%Y'), 2, 90);
INSERT INTO `mydb`.`Alquila` (`Vehículo_Matricula_V`, `Cliente_DNI_C`, `FechaAlquiler_CV`, `Duracion_CV`, `Precio_CV`) VALUES ('ABCD012', 321789654, str_to_date('01/07/2020', '%d/%m/%Y'), 4, 170);
INSERT INTO `mydb`.`Alquila` (`Vehículo_Matricula_V`, `Cliente_DNI_C`, `FechaAlquiler_CV`, `Duracion_CV`, `Precio_CV`) VALUES ('GHIJ567', 321789654, str_to_date('01/12/2020', '%d/%m/%Y'), 1, 50);
INSERT INTO `mydb`.`Alquila` (`Vehículo_Matricula_V`, `Cliente_DNI_C`, `FechaAlquiler_CV`, `Duracion_CV`, `Precio_CV`) VALUES ('IJKL789', 987654321, str_to_date('20/01/2020', '%d/%m/%Y'), 3, 135);
INSERT INTO `mydb`.`Alquila` (`Vehículo_Matricula_V`, `Cliente_DNI_C`, `FechaAlquiler_CV`, `Duracion_CV`, `Precio_CV`) VALUES ('IJKL789', 987123456, str_to_date('31/10/2020', '%d/%m/%Y'), 1, 50);
INSERT INTO `mydb`.`Alquila` (`Vehículo_Matricula_V`, `Cliente_DNI_C`, `FechaAlquiler_CV`, `Duracion_CV`, `Precio_CV`) VALUES ('ABCD123', 654987321, str_to_date('15/01/2020', '%d/%m/%Y'), 2, 90);
INSERT INTO `mydb`.`Alquila` (`Vehículo_Matricula_V`, `Cliente_DNI_C`, `FechaAlquiler_CV`, `Duracion_CV`, `Precio_CV`) VALUES ('ABCD123', 654987321, str_to_date('30/10/2020', '%d/%m/%Y'), 2, 90);
COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`ayuda`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`ayuda` (`identificadorDonante_S`, `identificadorRecibe_S`, `FechaAyuda_SS`, `Cantidad_SS`) VALUES (4, 1, str_to_date('01/01/2021', '%d/%m/%Y'), 2);
INSERT INTO `mydb`.`ayuda` (`identificadorDonante_S`, `identificadorRecibe_S`, `FechaAyuda_SS`, `Cantidad_SS`) VALUES (2, 1, str_to_date('01/01/2021', '%d/%m/%Y'), 1);
INSERT INTO `mydb`.`ayuda` (`identificadorDonante_S`, `identificadorRecibe_S`, `FechaAyuda_SS`, `Cantidad_SS`) VALUES (3, 2, str_to_date('15/09/2020', '%d/%m/%Y'), 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`asegura`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`asegura` (`Matricula_V`, `Nombre_A`, `NombreDueño_A`, `DNI_C`, `PrecioSeguro_CVA`,`FechaAlquiler_CVA`) VALUES ('IJKL678', 'Seguros del Norte', 'Pedro Martinez ', 789123456, 100, str_to_date('15/08/2021', '%d/%m/%Y'));
INSERT INTO `mydb`.`asegura` (`Matricula_V`, `Nombre_A`, `NombreDueño_A`, `DNI_C`, `PrecioSeguro_CVA`,`FechaAlquiler_CVA`) VALUES ('EFGH345', 'Seguros del Norte', 'Pedro Martinez ', 789123456, 100, str_to_date('16/08/2021', '%d/%m/%Y'));
INSERT INTO `mydb`.`asegura` (`Matricula_V`, `Nombre_A`, `NombreDueño_A`, `DNI_C`, `PrecioSeguro_CVA`,`FechaAlquiler_CVA`) VALUES ('UVWX678', 'Seguros del Norte', 'Pedro Martinez ', 789123456, 100, str_to_date('17/08/2021', '%d/%m/%Y'));
INSERT INTO `mydb`.`asegura` (`Matricula_V`, `Nombre_A`, `NombreDueño_A`, `DNI_C`, `PrecioSeguro_CVA`,`FechaAlquiler_CVA`) VALUES ('QRST345', 'Seguros del Norte', 'Pedro Martinez ', 789123456, 100, str_to_date('18/08/2021', '%d/%m/%Y'));
INSERT INTO `mydb`.`asegura` (`Matricula_V`, `Nombre_A`, `NombreDueño_A`, `DNI_C`, `PrecioSeguro_CVA`,`FechaAlquiler_CVA`) VALUES ('EFGH345', 'Protección Total', 'Fernando Alonso', 987654321, 200, str_to_date('12/11/2020', '%d/%m/%Y'));

COMMIT;


